### ISSUE TITLE
프로젝트 피드백

### ISSUE THREAD

**Issue by kangddong** [qockqock/MacAProject#15]
## 잘하신점
디자인 하셨던 분이 있으셨나요 ? 앱이 정말 깔끔하게 나왔네요 ! 고생하셨습니다 !
리드미도 너무 잘 꾸며주셨네요
MVC를 시도해보실려고한 부분이 인상깊었어요 ! 목적성이 흔들리지않게 코드리뷰를 통해서 중간중간 흐름을 잡아주면 좋을거같아요 ~

## delegate 활용에 대해
객체의 역할과 책임을 대신해주는 패턴에 대해서 학습, 적극적으로 적용하신 것은 짧은 시간이었음에도 고생하셨다고 말씀드립니다 ~
앞으로 언제 delegate를 활용하면 좋을지 ! 고민해보면서, 사용하면서 익혀보시고 개념도 계속 확인해보셨으면해요 !
### 네이밍 & 컨벤션
https://github.com/qockqock/MacAProject/blob/e9c069b2c78ff9f649f4c0dd5691e16032e03c47/MacAProject/Model/Model.swift#L9-L14
- 스네이크케이스를 특별하게 사용한 이유가 없다면 일반적인 카멜케이스가 좋을거같아요 !
- 배열로 담기 전에 목록에 대한 내용이 없다면 List, Array와 같은 네이밍은 지양하는게 좋을거같아요

https://github.com/qockqock/MacAProject/blob/e9c069b2c78ff9f649f4c0dd5691e16032e03c47/MacAProject/Model/Basket.swift#L10-L14
- 실제로 BasketItem의 coffee의 타입이 CoffeeList가 되니 목록의 성격을 띄는거같아서 오해의 소지가 생길거같아요 !

https://github.com/qockqock/MacAProject/blob/e9c069b2c78ff9f649f4c0dd5691e16032e03c47/MacAProject/Model/Basket.swift#L16-L18
- Swift 네이밍 규칙에서 약어는 지양합니다.
유추하자면 singletoneclass를 사용하고 싶었던거같아요 ! `default`, `shared` 와 같은 명명이 일반적입니다.
[API Design Guidelines-Use Terminology Well 참고](https://www.swift.org/documentation/api-design-guidelines/#naming)
![image](https://github.com/qockqock/MacAProject/assets/50406861/757aa545-7283-489f-9ec6-35250868118f)

- 코드리뷰 방식 개선
  - 이슈에 대해서 이야기가 길어지거나, 큰 이슈가 없다면 직접 모여서 하기보다는 github 코드리뷰 기능에 익숙해지는 걸 추천드립니다 !

**Comment by kangddong** [comment]
@dkswlgus0314 @qockqock @DeukRyoeng @Leedoseo 
추가적으로 궁금하신 부분은 코멘트 남기셔도됩니당
다음 과제 제출까지 이슈 열어두겠습니다

**Comment by DeukRyoeng** [comment]
@kangddong 리뷰 감사합니다 !!!!!!!!
